export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const SET_ERROR = 'SET_ERROR';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED =  'PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_INIT = 'PURCHASE_INIT'
export const PURCHASE_BURGER_ORDER ='PURCHASE_BURGER_ORDER'

export const FETCH_ORDER_INIT = 'FETCH_ORDER_INIT';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED'
export const FETCH_ORDER_START = 'FETCH_ORDER_START'
export const FETCH_ORDER_INIT_START = 'FETCH_ORDER_INIT_START'

export const DELETE_ORDER_START = 'DELETE_ORDER_START'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED'
export const DELETE_ORDER = 'DELETE_ORDER'
export const DELETE_ORDER_INITIATED = 'DELETE_ORDER_INITIATED'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT'
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT'
export const AUTH_USER = 'AUTH_USER'
export const AUTH_CHECK_INITIAL_STATE = 'AUTH_CHECK_INITIAL_STATE'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'